### ISSUE TITLE
feature request: labels for sequences

### ISSUE THREAD

**Issue by pariasm** [kidanger/vpv#13]
I'm not entirely sure that this is a feature that a video viewer should have. But maybe others find it also useful: give a name to each sequence shown in each window (from the gui or the cli). This name could be overlayed with reasonably sized fonts on a corner. Currently, this can be done with svgs, but having it as an option would be nice. It would be useful when showing results to other people. I often have to say out loud what I'm showing each time I hit space ("method 1, now method 2, now method 3," etc.).

**Comment by kidanger** [comment]
This is now quite easy to do with SVG from commit 948ef431bf6fd417f6cf83bdee6f06178cbf844b.
Example:
```svg
<svg width='1' height='1'>
<text font-size='50' fill='orange' x='0' y='0' display='absolute'>Input</text>
</svg>
```
```bash
$ vpv inputs/ svg:input.svg
```
