### ISSUE TITLE
Saturation cut with NaN in image

### ISSUE THREAD

**Issue by glostis** [kidanger/vpv#17]
When using the `alt+a` shortcut on an image containing some `NaN` values, the display goes completely black because the bounds of the shader become very large (1e+38..1e-38 on my example image). I guess not-a-number values must be read as being a very large value?

You can use the following example image to test:
[s1a-iw1-slc-vv-20150813t103221-20150813t103249-007243-009eaa-001.tiff.zip](https://github.com/kidanger/vpv/files/1781287/s1a-iw1-slc-vv-20150813t103221-20150813t103249-007243-009eaa-001.tiff.zip)

**Comment by kidanger** [comment]
Thanks for the report. Fixed since 9168c1a7b59db3091f8a9c785f6716dd10503506.

**Comment by glostis** [comment]
Thank you for the fix
