### ISSUE TITLE
Document installation and requirements

### ISSUE THREAD

**Issue by mazzma12** [kidanger/vpv#19]
Great work you have done here ! Just to add a few details about the installation :

* `cmake` is needed (okey it sounds obvious)
* `lib` library should be installed with the `dev` version. On Ubuntu 16.04 I had `libtiff5` but it raised an error at install time, I had to download `libtiff-dev` 
* we install in sudo so in ubuntu it added a binary in `/usr/local/bin` so there is no need to add it in the `PATH`

Again, these are just small hickups, the work is great ! I can PR the changes if you want.

**Comment by kidanger** [comment]
Thanks for the suggestions. Hopefully fixed by 8777624afc1495bfc3918774e91a4f6cb93aee0e

**Comment by mazzma12** [comment]
great. I would just add that you need the `dev` versions of the libraries to make explicit the difference between `libtiff5` and `libtiff-dev` libraries
