### ISSUE TITLE
Remove trailing slash in filepath

### ISSUE THREAD

**Issue by glostis** [kidanger/vpv#21]
I am in `root` and I have a directory named `timeseries` underneath. Launching `vpv` with the following command in `root`:

```
vpv timeseries/
```

causes a slight bug in the filepath displayed in the player's title:

```
timeseries//a.tiff
```

(see attached screenshot)
<img width="231" alt="vpv_bug" src="https://user-images.githubusercontent.com/25295717/40925276-a9d32308-6819-11e8-898c-3f44d222106f.png">

The user can avoid this problem by changing the call to:
```
vpv timeseries
```
but there might be a way to fix it at vpv's level.

**Comment by kidanger** [comment]
Thanks for the suggestion. Fixed by 5afa3701f8174547f74ec27c23201e3db64d9950.
