### ISSUE TITLE
alt-a is scared of nans

### ISSUE THREAD

**Issue by chlsl** [kidanger/vpv#38]
The attached image is a tif with floating point data containing a lot of nans.
As I wanted to automatically adjust the contrast of this image with alt-a, I was surprised to get a full black image, even after cycling with more alt-a (the displayed range was consistently 3.4e+38..-3.4e+38). Shift-a handles them nicely though.
Get the image at: https://www.dropbox.com/s/qlg4thnlpbejkl2/test_image.tif?dl=0

**Comment by kidanger** [comment]
Fixed in 2eb5bc6d6983a62c966ae4d9548fc0e6d7947a69.
Thanks for the bug report!

**Comment by chlsl** [comment]
It works like a charm now. Thanks for the fix!
