### ISSUE TITLE
player window disappears

### ISSUE THREAD

**Issue by pariasm** [kidanger/vpv#44]
The player windows have a check box allows to detach them from the main menu as a window floating inside vpv. This window is visible until one clicks outside of it. Then it disapears. Sometimes I need to jump to several specific frames in a video. To avoid loading every frame, I use the player, and I'd like to have it open, be able to inspect a frame, or a region in the frame, and move on to the next frame without having to reopen the player.

![image](https://user-images.githubusercontent.com/4415474/83971284-ef56c700-a8da-11ea-851a-48974d1b77b9.png)

**Comment by kidanger** [comment]
So the player window should always stay on top of other windows? Then the user could click the close button to make disappear.

For the moment, you can also use alt+<num> instead of the main menu to open a player.

**Comment by pariasm** [comment]
Yes, I use alt+. I think the player should stay on top until the user chooses to close it (at least for me).

**Comment by kidanger** [comment]
I pushed the change on dev 339869561876f952c10b9bc83bae34fcf7a1534c.
If it gets annoying I will revert it but for now it seems good.

Thanks!
