### ISSUE TITLE
problem with screenshots

### ISSUE THREAD

**Issue by pariasm** [kidanger/vpv#47]
The first screenshot it outputs a file 
`screenshot_%d.png`
i.e. without substituting the %d by the number.

The second screenshot it stalls, consuming 100% of CPU until killed.

```
~/S/vpv-dev$ vpv ~/Work/denoising/data/derf-hd/tractor/\*
Screenshot saved to 'screenshot_%d.png'.
fish: “vpv ~/Work/denoising/data/derf-…” terminated by signal SIGKILL (Forced quit)
```

**Comment by kidanger** [comment]
Can you send your `~/.vpvrc` and `build/luafiles.c` files ?

**Comment by pariasm** [comment]
[files.zip](https://github.com/kidanger/vpv/files/4858521/files.zip)

**Comment by kidanger** [comment]
```SCREENSHOT = 'screenshot_%%d.png'```

it should be set to `screenshot_%d.png`.

Cheers!
