### ISSUE TITLE
crash when entering edit mode

### ISSUE THREAD

**Issue by chlsl** [kidanger/vpv#50]
vpv consistently crashes when I press `e` to edit with plambda. For example, doing `vpv baboon_512x512_color.tif` then pressing `e` crashes, and the only message I get is: `[1]    3003 bus error  vpv baboon_512x512_color.tif`.

I'm on the dev branch at commit d2323a8dd076ff58bd5cadaaf5018a1886e1d259. I use the defaults when building with cmake.

Editing from the command line (`vpv baboon_512x512_color.tif e:"1 255 / sqrt"`) gives the same error.

I have no problem with my own version of plambda. For example, `plambda baboon_512x512_color.tif "255 / sqrt" | vpv` works.

**Comment by kidanger** [comment]
Is the issue still relevant? Some commit improved the stability of plambda on MacOS, it might be fixed.

**Comment by chlsl** [comment]
Indeed, I've just tested it, and I can't reproduce the error. I think we can close this issue.
