### ISSUE TITLE
Duplicated icons for "fit view" and "fit colormap"

### ISSUE THREAD

**Issue by chlsl** [kidanger/vpv#51]
Recently, I observed that the two icons that appear next to a selected area look duplicated with a small shift.
<img width="505" alt="Screenshot 2020-07-10 at 15 00 45" src="https://user-images.githubusercontent.com/32719781/87157181-234c5000-c2be-11ea-9923-cadd949ec134.png">
I'm at commit d2323a8dd076ff58bd5cadaaf5018a1886e1d259 on the dev branch.

**Comment by kidanger** [comment]
Thanks for the issue! Do you confirm that it is fixed?

**Comment by chlsl** [comment]
Yes, it's fixed! Thank you :)
