### ISSUE TITLE
strange heuristic in numpy reader

### ISSUE THREAD

**Issue by mnhrdt** [kidanger/vpv#65]
There is this code inside the numpy reader:

https://github.com/kidanger/vpv/blob/2db17cefa2de0e1f49ea7deadaac8220cb5c1fe2/src/ImageCollection.cpp#L279-L287

What is the rationale for this condition?  When you open a datacube it behaves very differently depending on the particular sizes of each side, and it is very confusing.

There does not seem to be the same logic for the tiff reader, which adds to the confusion.

**Comment by kidanger** [comment]
This is a heuristic to distinguish between two situations (given a shape (A, B, C)):
- an image of size AxB with C channels
- a sequence of A images of size BxC with 1 channel
Of course, this heuristic breaks with a hyperspectral image, or with a sequence of images having a small width. In these cases, the npy should be saved with 4 explicit dimensions.

The tiff reader does not yet support sequences of images, usually stored in a multi-page tiff.

**Comment by mnhrdt** [comment]
Thanks! Now I get it.

This heuristic is a bit disturbing, because it badly breaks the basic principle of "mechanism, not policy".  Both situations that you mention look identical from the point of view of the data structure involved (a 3-dimensional array of numbers), and this heuristic forces a distinction between them that is completely artificial.  I understand that this is a design choice of vpv, but it is confusing when you work with actual sequences that make the heuristic trigger.

Case in point: an image from the PRISMA instrument https://earth.esa.int/web/eoportal/satellite-missions/p/prisma-hyperspectral

Formally, the image is a 3-dimensional array of numbers, readily representable as a NPY file.  It is a sequence of 1000 images of size 256x1000 (acquired by a sensor of size 256x1000).  It is common to interpret it as 256 slices of size 1000x1000.  The current heuristic makes it almost impossible to open this file and understand what's going on.
