### ISSUE TITLE
parallel pre-caching of multiple images/sequences 

### ISSUE THREAD

**Issue by pariasm** [kidanger/vpv#8]
If I launch vpv as
`$ vpv lol\*`
the first image is quickly displayed and the program is responsive, while the others are pre-cached in a parallel thread. **But** if I launch vpv as
`$ vpv lol*`
Then vpv does not respond until all the images are loaded. This happens even if the program runs on full screen, so that a single image is begin displayed. This is different from the behaviour of pvflip (which would load each image on demand).

It would be nice if the pre-caching of the multiple images happens also in a parallel thread (at least in the full-screen view).

**Comment by kidanger** [comment]
This is fixed in the dev branch (for example, from commit 44d57ec9636f01a3f14cdd46403b18eb07946330). I encourage you to try out this version and tell me if this is how you expected it!
